### ISSUE TITLE
Calendar: Multi-day events appear as single day events in Month view

### ISSUE THREAD

**Issue by lmajerus** [VitalDevTeam/Center-for-Medical-Simulation#338]
Multi-day events should appear on the calendar (regardless of view) showing all dates like we see in Outlook, iCal, or Google calendars - the multi-day spans the days:
![screen shot 2017-05-19 at 8 07 53 am](https://cloud.githubusercontent.com/assets/22547623/26247110/60cd766c-3c6a-11e7-88e1-fd3b2d550fdf.png)

What we actually see on CMS Calendar https://harvardmedsim.org/calendar/
On Calendar page, as Month view - multi-day courses appear as though they are a single event repeated on each day which looks like the course is 1 day just held back-to-back days. Please change to overlap days breaking through the gridlines like shown in Google Calendar example above. Current view:
![screen shot 2017-05-18 at 10 57 04 am](https://cloud.githubusercontent.com/assets/22547623/26208779/fbdc94ba-3bb8-11e7-80f5-d9fd8aab95d9.png)

**Comment by mavedisian** [comment]
Hi @lmajerus, these changes were pushed live....

> Why is the Register Now button only showing with that specific event?
> This button shows when there is a website associated with Tribe's meta field called website (was hidden in development as we replaced it with custom internal / external links)

Because that field was replaced with our own, I dev'ed functionality to do the same thing with the internal / external / email fields you're used to using. 

> The Register Now CTA button is awesome. I think it should be there but the button text should be "Apply Now" rather than "Register Now".

Done.

> Why is the Register Now button showing up with a past event? I thought that you couldn't apply for past events. The logic on the Course pages Course Offerings table has the line for past courses disappear from both the Course page and the Course Application once the end date has past.

This will no longer happen, I've added logic to prevent it. 

Please review on staging.

**Comment by lmajerus** [comment]
Hi @mavedisian. It looks like some of the formatting & styling on staging moved over to production but others have not. Here are examples that did not seem to move to production yet: 

**Course Offerings table on Course pages (on production):**
The year needs to appear along with the month and date - only the day name, month, and date currently appear. This is fixed on staging (see below).
https://harvardmedsim.org/course/gateway-debriefing-skills-workshop/#course-offerings
![gateway-course-offerings-production](https://user-images.githubusercontent.com/22547623/27189150-7a7f85dc-51be-11e7-9f5b-b19166182db7.png)

**Course Offerings table on Course pages (on staging):**
http://harvardmedsim.staging.wpengine.com/course/gateway-debriefing-skills-workshop/#course-offerings
![gateway-course-offerings-staging](https://user-images.githubusercontent.com/22547623/27189165-849231e6-51be-11e7-9389-8f2e4ad13a11.png)

**List view (on production)**
Formatting of list view: the Date is indented further right than all other text (e.g. location and description) which you corrected on Staging (see below). Should be left aligned.
https://harvardmedsim.org/calendar/list/
![list events-upcoming-june-13-production](https://user-images.githubusercontent.com/22547623/27189523-9fcf781e-51bf-11e7-8558-f1623da2cf70.png)

**List view (on staging)**
http://harvardmedsim.staging.wpengine.com/calendar/list/
![list events-upcoming-june-13-staging](https://user-images.githubusercontent.com/22547623/27189539-af2e9088-51bf-11e7-9b52-9441d6d1d50c.png)

**Comment by lmajerus** [comment]
Hi @mavedisian, I've reviewed the new nifty feature in List view of showing a CTA button to both the event itself and the field for Apply Now (with desired results depending on Internal/External/Email). 2 issues:
1) Past events are still showing the Apply Now/Learn More/Email for Info CTA buttons.
On a related note, on the Event Details page for past events, the Apply Now/Learn More/Email for Info CTA buttons still appear too. Can you add logic to have these removed after the date has passed just like you are doing for the List view?

2) Apply Now CTA for internal events brings user correctly to the \apply-now application form and fills in the course type field. The problem is that it won't allow you to select a date from the drop-down nor does the selected date from the event auto-populate the Preferred Date drop-down so the applicant cannot proceed with the application. I think we had the same problem on the Course Offerings table on course pages. I thought you fixed that by only passing the person to the \apply-now page with the course type completed but not the specific date while allowing the user to select the date from drop-down list. I tested this on production page https://harvardmedsim.org/course/gateway-debriefing-skills-workshop/#course-offerings, clicking on the Aug 24, 2017 Apply Now and was correctly routed to the \apply-now application with Gateway as course type and allowed to select date from drop-down. Here's the url that results to repeat my steps to get to the \apply-now on production: https://harvardmedsim.org/apply-now/?course-id=218383&ref-page=473.

On staging, in List view http://harvardmedsim.staging.wpengine.com/calendar/list/, I scrolled down and selected the June 15, 2017 ACRMF6 Apply Now which passed me to /apply-now with this result URL that I cannot select the date from: http://harvardmedsim.staging.wpengine.com/apply-now/?course-id=218283. 

Um...ok I'm really confused. I repeated the steps for the Apply Now CTA from List view on staging and it seems that after a time delay (not sure how long), I'm suddenly able to use the Select Date drop down list. The time delay seems to be less than 30 seconds but I'm concerned people will be confused by this. Do you have any idea what's happening to cause the delay?

**Comment by lmajerus** [comment]
RE: List view date order on staging - the AJAX functionality seems to be working correctly. All the dates in List view appear in correct order. Please push this functionality to production.

**Comment by mavedisian** [comment]
Hi @lmajerus, just wanted to say thanks for bearing with me. There was a lot of information in this thread, so it took some time to completely understand some of the issues. Let's please try to keep issues separate in the future (Course type table issues vs. calendar issues) as it will help prevent long threads like this.

> Course Offerings table on Course pages (on production):
> The year needs to appear along with the month and date - only the day name, month, and date currently appear. This is fixed on staging (see below).
This is done, pushed to production. 

> List view (on production)
> Formatting of list view: the Date is indented further right than all other text (e.g. location and description) which you corrected on Staging (see below). Should be left aligned.
This is done, pushed to production. 

> Past events are still showing the Apply Now/Learn More/Email for Info CTA buttons.
> On a related note, on the Event Details page for past events, the Apply Now/Learn More/Email for Info CTA buttons still appear too. Can you add logic to have these removed after the date has passed just like you are doing for the List view?
I wasn't able to replicate the issue of past events having CTAs, but I did correct the CTAs showing in detailed view. This was pushed to production. 

> Apply Now CTA for internal events brings user correctly to the \apply-now application form and fills in the course type field. The problem is that it won't allow you to select a date from the drop-down nor does the selected date from the event auto-populate the Preferred Date drop-down so the applicant cannot proceed with the application. 
Based on my testing, it does work (as you later indicated). Passing in a referring course type page into the URL just saves the user the time of selecting the date they want. There is a slight delay because of the logic looping through the available dates and listing them. Perhaps there is a way to indicate there is some loading going on. 

> RE: List view date order on staging - the AJAX functionality seems to be working correctly. All the dates in List view appear in correct order. Please push this functionality to production.
This was pushed to production. 

Please review as there was a lot addressed and I'd like to make sure things are performing the way they should.

**Comment by lmajerus** [comment]
Original convoluted ticket covering multiple topics was separated into individual tickets to try and clarify items that are resolved versus still open.

This issue is resolved.
